"""Regression tests for starter programmes generated by ``rosh new``."""

from __future__ import annotations

from pathlib import Path

from rosh_lang.cli.scaffolder import _TEMPLATES
from rosh_lang.core.parser import parse_string
from rosh_lang.targets._js_codegen import compile_programme


ROOT = Path(__file__).parent.parent
REFERENCE_GAMES = (
    ROOT / "examples" / "reference-game.rosh",
    ROOT / "examples" / "showcase" / "18-reference-game.rosh",
)


def _assert_safe_lives_handler(source: str) -> None:
    assert 'if game-lifecycle.phase == "playing"' in source
    assert "send check-lives" in source
    assert "send lives.check-lives" not in source

    compiled = compile_programme(parse_string(source))
    assert 'rosh.get("game-lifecycle.phase") === "playing"' in compiled.handler_code
    assert 'rosh.set("lives.count"' in compiled.handler_code
    assert 'rosh.send("check-lives")' in compiled.handler_code


def test_game_scaffold_has_safe_lives_handler() -> None:
    source = _TEMPLATES["game"][1].replace("{name}", "test-game")
    _assert_safe_lives_handler(source)


def test_reference_games_match_safe_lifecycle_pattern() -> None:
    for path in REFERENCE_GAMES:
        _assert_safe_lives_handler(path.read_text(encoding="utf-8"))
